In [1]:
import numpy as np

In [2]:
a = [10,11,12,13,14,15]

In [3]:
import numpy as np

In [4]:
n_a = np.array(a)

In [5]:
n_a

array([10, 11, 12, 13, 14, 15])

In [6]:
n_a[0]

10

In [7]:
n_a[1]

11

In [8]:
last_index = len(n_a)-1

In [9]:
n_a[last_index]

15

In [10]:
n_a[-1]

15

In [12]:
n_a[-2]

14

In [13]:
n_a[0:3]

array([10, 11, 12])

In [15]:
n_a[3:6]

array([13, 14, 15])

In [16]:
n_a[3:]

array([13, 14, 15])

In [17]:
n_a[:3]

array([10, 11, 12])

In [18]:
n_a[2:4]

array([12, 13])

In [20]:
n_a[1:-1]

array([11, 12, 13, 14])

In [21]:
n_a[::2]

array([10, 12, 14])

In [22]:
n_a[1::2]

array([11, 13, 15])

In [23]:
n_b = np.array([100,101,102,103,104,105])

In [24]:
n_c = np.concatenate([n_a, n_b])

In [25]:
np.sum(n_c)

690

In [26]:
np.max(n_c)

105

In [27]:
np.min(n_c)

10

In [29]:
np.mean(n_c)

57.5

In [31]:
n_random = np.random.random(10)

In [32]:
n_random

array([0.0986236 , 0.27720557, 0.98572519, 0.16911208, 0.70383601,
       0.87465056, 0.89371229, 0.30851425, 0.2621151 , 0.05628638])

In [33]:
np.max(n_random)

0.9857251908792737

In [34]:
np.min(n_random)

0.05628637940582948

In [35]:
np.sort(n_random)

array([0.05628638, 0.0986236 , 0.16911208, 0.2621151 , 0.27720557,
       0.30851425, 0.70383601, 0.87465056, 0.89371229, 0.98572519])

In [36]:
np.argsort(n_random)

array([9, 0, 3, 8, 1, 7, 4, 5, 6, 2])

In [40]:
np.sort(n_random)[::-1]

array([0.98572519, 0.89371229, 0.87465056, 0.70383601, 0.30851425,
       0.27720557, 0.2621151 , 0.16911208, 0.0986236 , 0.05628638])