In [1]:
import numpy as np

In [2]:
a = [10,11,12,13,14,15]

In [3]:
import numpy as np

In [4]:
n_a = np.array(a)

In [5]:
n_a

array([10, 11, 12, 13, 14, 15])

In [6]:
n_a[0]

10

In [7]:
n_a[1]

11

In [8]:
last_index = len(n_a)-1

In [9]:
n_a[last_index]

15

In [10]:
n_a[-1]

15

In [12]:
n_a[-2]

14

In [13]:
n_a[0:3]

array([10, 11, 12])

In [15]:
n_a[3:6]

array([13, 14, 15])

In [16]:
n_a[3:]

array([13, 14, 15])

In [17]:
n_a[:3]

array([10, 11, 12])

In [18]:
n_a[2:4]

array([12, 13])

In [20]:
n_a[1:-1]

array([11, 12, 13, 14])

In [21]:
n_a[::2]

array([10, 12, 14])

In [22]:
n_a[1::2]

array([11, 13, 15])

In [23]:
n_b = np.array([100,101,102,103,104,105])

In [24]:
n_c = np.concatenate([n_a, n_b])